var namespacecom_1_1javicodema_1_1soccerstatsapp_1_1activitys_1_1_team =
[
    [ "AddEditTeamActivity", "classcom_1_1javicodema_1_1soccerstatsapp_1_1activitys_1_1_team_1_1_add_edit_team_activity.html", "classcom_1_1javicodema_1_1soccerstatsapp_1_1activitys_1_1_team_1_1_add_edit_team_activity" ],
    [ "TeamListActivity", "classcom_1_1javicodema_1_1soccerstatsapp_1_1activitys_1_1_team_1_1_team_list_activity.html", "classcom_1_1javicodema_1_1soccerstatsapp_1_1activitys_1_1_team_1_1_team_list_activity" ]
];